# This file is part of django-ca (https://github.com/mathiasertl/django-ca).
#
# django-ca is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# django-ca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with django-ca. If not, see
# <http://www.gnu.org/licenses/>.

"""Test the detail-view for a certificate."""
from http import HTTPStatus

from django.test import TestCase
from django.urls import reverse_lazy

from freezegun import freeze_time

from django_ca import ca_settings
from django_ca.models import Certificate
from django_ca.tests.api.mixins import APITestCaseMixin
from django_ca.tests.base import certs, timestamps
from django_ca.utils import x509_name


class CertificateDetailTestCase(APITestCaseMixin, TestCase):
    """Test the detail-view for a certificate."""

    path = reverse_lazy(
        "django_ca:api:view_certificate",
        kwargs={"serial": certs["root"]["serial"], "certificate_serial": certs["root-cert"]["serial"]},
    )
    required_permission = (Certificate, "view_certificate")
    load_certs = ("root-cert",)

    def setUp(self) -> None:
        super().setUp()
        cert = certs["root-cert"]
        self.cert.profile = ca_settings.CA_DEFAULT_PROFILE
        self.cert.save()
        self.expected_response = {
            "autogenerated": False,
            "created": self.iso_format(self.cert.created),
            "not_after": self.iso_format(self.cert.expires),
            "not_before": self.iso_format(self.cert.valid_from),
            "pem": cert["pub"]["pem"],
            "profile": self.cert.profile,
            "revoked": False,
            "serial": cert["serial"],
            "subject": x509_name(cert["subject"]).rfc4514_string(),
            "updated": self.iso_format(self.cert.updated),
        }

    @freeze_time(timestamps["everything_valid"])
    def test_detail_view(self) -> None:
        """Test an ordinary detail view."""
        response = self.default_request()
        self.assertEqual(response.status_code, HTTPStatus.OK, response.json())
        self.assertEqual(response.json(), self.expected_response, response.json())

    @freeze_time(timestamps["everything_expired"])
    def test_expired_certificate(self) -> None:
        """Test that we can view the certificate even if it is expired."""
        response = self.default_request()
        self.assertEqual(response.status_code, HTTPStatus.OK, response.json())
        self.assertEqual(response.json(), self.expected_response, response.json())

    @freeze_time(timestamps["everything_valid"])
    def test_disabled_ca(self) -> None:
        """Test that certificates for a disabled can *not* be viewed."""
        self.ca.enabled = False
        self.ca.save()

        response = self.default_request()
        self.assertEqual(response.status_code, HTTPStatus.NOT_FOUND, response.json())
        self.assertEqual(response.json(), {"detail": "Not Found"}, response.json())
