ARG IMAGE=debian:buster
FROM $IMAGE

RUN apt-get update && \
    apt-get install -y certbot curl && \
    rm -rf /var/lib/apt/lists/*
ADD ca/django_ca/tests/fixtures/cli.ini /etc/letsencrypt/cli.ini

WORKDIR /root/
