[tox]
envlist = pylint,docs,lint,mypy,demo,pkg
          py{311,312,313,314}-dj{5.2}-cg{49}-acme{5.4,5.5,5.6}-pydantic{2.12,2.13}
          py{312,313,314}-dj{6.0}-cg{49}-acme{5.4,5.5,5.6}-pydantic{2.12,2.13}
          faketime

[testenv]
skipsdist = True
package = wheel
wheel_build_env = .pkg
runner = uv-venv-lock-runner
extras =
    api
    celery
    hsm
dependency_groups =
    dev
    dj5.2: Django5.2
    dj6.0: Django6.0
    cg49: cryptography49
    acme5.4: acme5.4
    acme5.5: acme5.5
    acme5.6: acme5.6
    pydantic2.12: pydantic2.12
    pydantic2.13: pydantic2.13
setenv =
    COVERAGE_FILE = {envdir}/.coverage
commands =
    pytest -vx --basetemp="{env_tmp_dir}" --cov-report html:{envdir}/htmlcov/ --durations=20 {posargs}

[testenv:faketime]
setenv =
    COVERAGE_FILE = {envdir}/.coverage
allowlist_externals = faketime
commands =
    faketime -f "+100y" pytest -vx --no-selenium --basetemp="{env_tmp_dir}" --cov-report html:{envdir}/htmlcov/ --durations=20 {posargs}

[testenv:demo]
allowlist_externals = rm
commands =
    rm -rf {envdir}/db.sqlite3 {envdir}/files/
    python dev.py init-demo

[testenv:lint]
dependency_groups = dev, lint
commands =
    python dev.py code-quality
    python dev.py validate state
    python dev.py validate license-headers

[testenv:pylint]
dependency_groups = dev, lint
commands =
    pylint ca/ca/ ca/django_ca/ docs/source/django_ca_sphinx/ devscripts/ dev.py

[testenv:docs]
#basepython = python3.12
dependency_groups = dev, docs
allowlist_externals = make
commands =
    doc8 docs/source/
    make -C docs clean spelling html

[testenv:mypy]
# Add redis extra, hiredis has typehints
dependency_groups = dev, mypy
extras =
    api
    celery
    hsm
    redis
commands = mypy .

[testenv:pkg]
commands =
    uv build
