# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('expires', models.DateTimeField()),
                ('csr', models.TextField()),
                ('pub', models.TextField()),
                ('cn', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=35)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_date', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('watchers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
