# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='serial',
            field=models.CharField(max_length=48),
        ),
    ]
