# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0003_auto_20151227_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='watchers',
        ),
    ]
