# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0005_certificate_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='certificates', to='django_ca.Watcher'),
        ),
    ]
