# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0005_certificateauthority_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='private_key_path',
            field=models.CharField(default='', help_text='Path to the private key.', max_length=256),
            preserve_default=False,
        ),
    ]
