# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 20:50
from __future__ import unicode_literals

from django.db import migrations

def compute_serial(apps, schema_editor):
    CertificateAuthority = apps.get_model('django_ca', 'CertificateAuthority')
    for ca in CertificateAuthority.objects.all():
        s = hex(ca.x509.get_serial_number())[2:].upper()
        ca.serial = ':'.join(a+b for a,b in zip(s[::2], s[1::2]))
        ca.save()

class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0006_certificate_ca'),
    ]

    operations = [
    ]
