# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0006_auto_20160228_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_ca.CertificateAuthority', verbose_name='Certificate Authority'),
            preserve_default=False,
        ),
    ]
