# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_ca.utils


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0007_auto_20160313_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='crl_url',
            field=models.TextField(blank=True, help_text='URLs, one per line, where you can retrieve the CRL.', null=True, validators=[django_ca.utils.multiline_url_validator], verbose_name='CRL URLs'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='issuer_alt_name',
            field=models.URLField(blank=True, help_text='URL for your CA.', null=True, verbose_name='issuerAltName'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='issuer_url',
            field=models.URLField(blank=True, help_text='URL where to view additional info about your CA.', null=True, verbose_name='Issuer URL'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_url',
            field=models.URLField(blank=True, help_text='URL of a OCSP responser for the CA.', null=True, verbose_name='OCSP responder URL'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='serial',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='serial',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
