# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0007_certificate_ca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateauthority',
            options={'verbose_name': 'Certificate Authority', 'verbose_name_plural': 'Certificate Authorities'},
        ),
    ]
