# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0008_auto_20160313_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='issuer_url',
            field=models.URLField(blank=True, help_text='URL to the certificate of this CA (in DER format).', null=True, verbose_name='Issuer URL'),
        ),
    ]
