# Generated by Django 2.1.4 on 2018-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0008_auto_20171203_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='private_key_path',
            field=models.FileField(help_text='Path to the private key.', upload_to='files'),
        ),
    ]
