# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0008_auto_20160302_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='name',
            field=models.CharField(help_text='A human-readable name', max_length=32, unique=True),
        ),
    ]
