# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0009_auto_20160325_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-Mail'),
        ),
    ]
