# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0010_auto_20160421_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='cn',
            field=models.CharField(default='tmp', max_length=64, verbose_name='CommonName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 22, 0, 15, 373419)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='revoked_reason',
            field=models.CharField(blank=True, choices=[('', 'No reason'), ('unspecified', 'Unspecified'), ('keyCompromise', 'Key compromised'), ('CACompromise', 'CA compromised'), ('affiliationChanged', 'Affiliation changed'), ('superseded', 'Superseded'), ('cessationOfOperation', 'Cessation of operation'), ('certificateHold', 'On Hold')], max_length=32, null=True, verbose_name='Reason for revokation'),
        ),
    ]
