# This file is part of django-ca (https://github.com/mathiasertl/django-ca).
#
# django-ca is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# django-ca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with django-ca. If not, see
# <http://www.gnu.org/licenses/>.

# Generated by Django 3.0.2 on 2020-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ca", "0018_certificate_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="autogenerated",
            field=models.BooleanField(
                default=False, help_text="If this certificate was automatically generated."
            ),
        ),
    ]
