# Generated by Django 3.0.6 on 2020-06-11 16:09

from django.db import migrations, models
import django.db.models.deletion
import django_ca.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0020_acmeaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=django_ca.models.acme_slug, unique=True)),
                ('status', models.CharField(choices=[('invalid', 'Invalid'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('valid', 'Valid')], default='pending', max_length=10)),
                ('expires', models.DateTimeField(default=django_ca.models.acme_order_expires)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ca.AcmeAccount')),
            ],
        ),
        migrations.CreateModel(
            name='AcmeAccountAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=django_ca.models.acme_slug, unique=True)),
                ('type', models.CharField(choices=[('dns', 'DNS')], default='dns', max_length=8)),
                ('value', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ca.AcmeOrder')),
            ],
        ),
    ]
