# Generated by Django 3.1.4 on 2020-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0020_auto_20201208_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='acme_enabled',
            field=models.BooleanField(default=False, help_text='Whether it is possible to use ACME for this CA.', verbose_name='Enable ACME'),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='acme_requires_contact',
            field=models.BooleanField(default=True, help_text='If this CA requires a contact address during account registration.', verbose_name='Requires contact'),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='acme_terms_of_service',
            field=models.URLField(blank=True, help_text='URL to Terms of Service for this CA', verbose_name='Terms of Service'),
        ),
    ]
