# Generated by Django 3.1.4 on 2020-12-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0021_auto_20201210_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateauthority',
            old_name='acme_terms_of_service',
            new_name='terms_of_service',
        ),
    ]
