# Generated by Django 3.0.7 on 2020-06-21 15:38

from django.db import migrations, models
import django.db.models.deletion
import django_ca.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0021_acmeaccountauthorization_acmeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=django_ca.models.acme_slug, unique=True)),
                ('type', models.CharField(choices=[('http-01', 'HTTP Challenge'), ('dns-01', 'DNS Challenge'), ('tls-alpn-01', 'TLS ALPN Challenge')], max_length=12)),
                ('status', models.CharField(choices=[('http-01', 'HTTP Challenge'), ('dns-01', 'DNS Challenge'), ('tls-alpn-01', 'TLS ALPN Challenge')], max_length=12)),
                ('validated', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=64)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ca.AcmeAccountAuthorization')),
            ],
        ),
    ]
