# Generated by Django 3.2 on 2021-04-26 13:40

from django.db import migrations

from cryptography import x509


def migrate_csr(apps, schema_editor):
    Certificate = apps.get_model("django_ca", "Certificate")
    for cert in Certificate.objects.exclude(csr=""):
        try:
            csr = x509.load_pem_x509_csr(cert.csr.encode())
        except Exception:
            print(f"{cert}: Could not convert CSR.")
            continue
        cert.csr_tmp = csr
        cert.save()


def noop(apps, schema_editor):
    """no need to do anything in backwards data migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0022_certificate_csr_tmp'),
    ]

    operations = [
        migrations.RunPython(migrate_csr, noop),
    ]
