# Generated by Django 3.2 on 2021-04-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0023_auto_20210426_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='csr',
        ),
    ]
