# Generated by Django 3.1 on 2020-08-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0023_auto_20200621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmechallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('valid', 'Valid'), ('invalid', 'Name')], default='pending', max_length=12),
        ),
    ]
