# Generated by Django 3.1 on 2020-08-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0024_auto_20200822_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmeaccount',
            options={'verbose_name': 'ACME Account', 'verbose_name_plural': 'ACME Accounts'},
        ),
        migrations.AlterModelOptions(
            name='acmeaccountauthorization',
            options={'verbose_name': 'ACME Account Authorization', 'verbose_name_plural': 'ACME Account Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='acmechallenge',
            options={'verbose_name': 'ACME Challenge', 'verbose_name_plural': 'ACME Challenges'},
        ),
        migrations.AlterModelOptions(
            name='acmeorder',
            options={'verbose_name': 'ACME Order', 'verbose_name_plural': 'ACME Orders'},
        ),
    ]
