# Generated by Django 3.2 on 2021-04-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0024_remove_certificate_csr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='csr_tmp',
            new_name='csr',
        ),
    ]
