# Generated by Django 3.1.1 on 2020-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0025_auto_20200822_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmeaccount',
            name='thumbprint',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
