# Generated by Django 3.2 on 2021-04-28 23:54

from django.db import migrations
import django_ca.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0025_rename_csr_tmp_certificate_csr'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pub_tmp',
            field=django_ca.modelfields.CertificateField(verbose_name='Public key'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='pub_tmp',
            field=django_ca.modelfields.CertificateField(verbose_name='Public key'),
        ),
    ]
