# Generated by Django 3.1.1 on 2020-09-26 15:56

from django.db import migrations, models
import django.db.models.deletion
import django_ca.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0026_acmeaccount_thumbprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeaccountauthorization',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='django_ca.acmeorder'),
        ),
        migrations.CreateModel(
            name='AcmeCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=django_ca.models.acme_slug, unique=True)),
                ('csr', models.TextField(verbose_name='CSR')),
                ('cert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ca.certificate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ca.acmeorder')),
            ],
        ),
    ]
