# This file is part of django-ca (https://github.com/mathiasertl/django-ca).
#
# django-ca is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# django-ca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with django-ca. If not, see
# <http://www.gnu.org/licenses/>.

# Generated by Django 4.1.4 on 2022-12-25 22:22

from django.db import migrations, models

import django_ca.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ca", "0026_auto_20210501_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateauthority",
            name="acme_profile",
            field=models.CharField(
                default=django_ca.models.default_profile,
                help_text="Profile used when generating ACME certificates.",
                max_length=32,
                verbose_name="Profile",
            ),
        ),
    ]
