# Generated by Django 4.1.4 on 2022-12-25 22:22

from django.db import migrations, models

import django_ca.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ca", "0026_auto_20210501_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateauthority",
            name="acme_profile",
            field=models.CharField(
                default=django_ca.models.default_profile,
                help_text="Profile used when generating ACME certificates.",
                max_length=32,
                verbose_name="Profile",
            ),
        ),
    ]
