# Generated by Django 3.1.2 on 2020-10-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0027_auto_20200926_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmeaccount',
            name='ca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_ca.certificateauthority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acmeaccount',
            name='pem',
            field=models.TextField(unique=True, verbose_name='Public key'),
        ),
        migrations.AlterUniqueTogether(
            name='acmeaccount',
            unique_together={('ca', 'thumbprint')},
        ),
    ]
