# Generated by Django 3.1.2 on 2020-10-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0028_auto_20201017_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeaccount',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('deactivated', 'Deactivated'), ('revoked', 'Revoked')], default='valid', max_length=12),
        ),
        migrations.AlterField(
            model_name='acmeaccountauthorization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('deactivated', 'Deactivated'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=12),
        ),
    ]
