# Generated by Django 3.1.2 on 2020-10-24 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0029_auto_20201024_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmeorder',
            name='not_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='acmeorder',
            name='not_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='acmeorder',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='django_ca.acmeaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='acmeaccountauthorization',
            unique_together={('order', 'type', 'value')},
        ),
    ]
