# Generated by Django 3.1.2 on 2020-10-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0030_auto_20201024_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmecertificate',
            options={'verbose_name': 'ACME Certificate', 'verbose_name_plural': 'ACME Certificate'},
        ),
        migrations.AlterField(
            model_name='acmecertificate',
            name='cert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ca.certificate', unique=True),
        ),
        migrations.AlterField(
            model_name='acmecertificate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ca.acmeorder', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='acmechallenge',
            unique_together={('auth', 'type')},
        ),
    ]
