# Generated by Django 3.1.2 on 2020-10-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0031_auto_20201026_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmecertificate',
            name='cert',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ca.certificate'),
        ),
        migrations.AlterField(
            model_name='acmecertificate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_ca.acmeorder'),
        ),
    ]
