# Generated by Django 3.1.3 on 2020-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0033_auto_20201114_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='acme_enabled',
            field=models.BooleanField(default=False, help_text='Whether it is possible to use ACME for this CA.'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='acme_terms_of_service',
            field=models.URLField(blank=True, help_text='Terms of Service for this CA'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='caa_identity',
            field=models.CharField(blank=True, help_text='CAA identity for this CA (NOTE: Not currently used!).', max_length=32, verbose_name='CAA identity'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='website',
            field=models.URLField(blank=True, help_text='Website for your CA.'),
        ),
        migrations.AlterField(
            model_name='acmeaccount',
            name='contact',
            field=models.TextField(blank=True, help_text='Contact addresses for this account, one per line.'),
        ),
    ]
