# Generated by Django 3.1.3 on 2020-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0034_auto_20201115_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='acme_requires_contact',
            field=models.BooleanField(default=True, help_text='If this CA requires a contact address during account registration.'),
        ),
    ]
