# Generated by Django 4.2.6 on 2023-10-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ca", "0035_certificateorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateauthority",
            name="api_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether it is possible to use the API for this CA.",
                verbose_name="Enable API",
            ),
        ),
    ]
