# Generated by Django 5.0 on 2023-12-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ca", "0036_certificateauthority_api_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificateauthority",
            name="name",
            field=models.CharField(
                help_text="A human-readable name", max_length=256, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="certificateorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Choices"),
                    ("failed", "Failed"),
                    ("issued", "Issued"),
                ],
                default="pending",
                help_text="Current status of the order.",
                max_length=8,
            ),
        ),
    ]
