# Generated by Django 3.1.3 on 2020-12-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0036_auto_20201128_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcmeAccountAuthorization',
            new_name='AcmeAuthorization',
        ),
        migrations.AlterModelOptions(
            name='acmeauthorization',
            options={'verbose_name': 'ACME Authorization', 'verbose_name_plural': 'ACME Authorizations'},
        ),
    ]
