# Generated by Django 3.1.3 on 2020-12-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0038_auto_20201206_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acmeaccount',
            old_name='acme_kid',
            new_name='kid',
        ),
    ]
