# Generated by Django 5.0.2 on 2024-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ca", "0041_remove_certificateauthority_crl_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificateauthority",
            name="key_backend_options",
            field=models.JSONField(default=dict, help_text="Key backend options"),
        ),
        migrations.AddField(
            model_name="certificateauthority",
            name="key_backend_path",
            field=models.CharField(
                default="django_ca.backends.storages.StoragesBackend",
                help_text="Backend to handle private keys.",
                max_length=256,
            ),
            preserve_default=False,
        ),
    ]
