# Generated by Django 5.1.1 on 2024-10-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0044_remove_certificateauthority_private_key_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='valid_from',
            new_name='not_before',
        ),
        migrations.RenameField(
            model_name='certificateauthority',
            old_name='valid_from',
            new_name='not_before',
        ),
    ]
