# Generated by Django 5.1.1 on 2024-10-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0045_rename_valid_from_certificate_not_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='expires',
            new_name='not_after',
        ),
        migrations.RenameField(
            model_name='certificateauthority',
            old_name='expires',
            new_name='not_after',
        ),
    ]
