# Generated by Django 5.1.2 on 2024-10-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0048_auto_20241017_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateauthority',
            name='crl_number',
        ),
    ]
