# Generated by Django 5.1.3 on 2024-12-01 19:37

import django_ca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0049_remove_certificateauthority_crl_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_key_backend_alias',
            field=models.CharField(default='default', help_text='Backend to handle private keys for OCSP responder certificates.', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_key_backend_options',
            field=models.JSONField(blank=True, default=django_ca.models.ocsp_key_backend_options_default, help_text='Key backend options for using OCSP responder private keys.'),
        ),
    ]
