# Generated by Django 5.2 on 2025-04-19 19:45

import django_ca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0051_auto_20241201_2038'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificaterevocationlist',
            name='django_ca_c_ca_id_965937_idx',
        ),
        migrations.AlterField(
            model_name='acmeaccount',
            name='pem',
            field=models.TextField(validators=[django_ca.models.pem_validator], verbose_name='Public key'),
        ),
        migrations.AlterField(
            model_name='acmeaccount',
            name='thumbprint',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='certificaterevocationlist',
            index=models.Index(fields=['ca', 'number', 'only_contains_user_certs', 'only_contains_ca_certs', 'only_contains_attribute_certs'], name='django_ca_c_ca_id_c93eda_idx'),
        ),
    ]
