# Generated by Django 5.2 on 2025-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0051_auto_20241201_2038'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificaterevocationlist',
            name='django_ca_c_ca_id_965937_idx',
        ),
        migrations.AddIndex(
            model_name='certificaterevocationlist',
            index=models.Index(fields=['ca', 'number', 'only_contains_user_certs', 'only_contains_ca_certs', 'only_contains_attribute_certs'], name='django_ca_c_ca_id_c93eda_idx'),
        ),
    ]
