# Generated by Django 5.2 on 2025-04-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0001_squashed_0052_remove_certificaterevocationlist_django_ca_c_ca_id_965937_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='not_before',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='key_backend_alias',
            field=models.CharField(help_text='Backend to handle private keys.', max_length=256),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='not_before',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='ocsp_key_backend_alias',
            field=models.CharField(help_text='Backend to handle private keys for OCSP responder certificates.', max_length=256),
        ),
    ]
