# Generated by Django 5.2.4 on 2025-07-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0001_squashed_0052_remove_certificaterevocationlist_django_ca_c_ca_id_965937_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmechallenge',
            name='type',
            field=models.CharField(choices=[('http-01', 'HTTP Challenge'), ('dns-01', 'DNS Challenge')], max_length=12),
        ),
    ]
