# Generated by Django 5.2.4 on 2025-07-12 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0053_alter_acmechallenge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='serial',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[1-9A-F][0-9A-F]*$')]),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='serial',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[1-9A-F][0-9A-F]*$')]),
        ),
    ]
