# Generated by Django 5.2.6 on 2025-09-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0054_alter_certificate_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cn',
            field=models.CharField(blank=True, max_length=128, verbose_name='CommonName'),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='cn',
            field=models.CharField(blank=True, max_length=128, verbose_name='CommonName'),
        ),
    ]
