# Generated by Django 6.0.4 on 2026-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0055_alter_certificate_cn_alter_certificateauthority_cn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='name',
            field=models.CharField(help_text='A human-readable name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='watcher',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CommonName'),
        ),
    ]
