# Generated by Django 6.0.4 on 2026-05-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0056_alter_certificateauthority_name_alter_watcher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateExpiryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='django_ca.certificate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
