# Generated by Django 6.0.4 on 2026-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0057_certificateexpirynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='ocsp_response',
            field=models.BinaryField(blank=True, help_text='Cached DER-encoded OCSP response for this certificate.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='ocsp_response_expires',
            field=models.DateTimeField(blank=True, help_text='Expiry time of the cached OCSP response.', null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_response',
            field=models.BinaryField(blank=True, help_text='Cached DER-encoded OCSP response for this certificate.', null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_response_expires',
            field=models.DateTimeField(blank=True, help_text='Expiry time of the cached OCSP response.', null=True),
        ),
    ]
