# Generated by Django 6.0.8 on 2026-08-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0058_certificate_ocsp_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeauthorization',
            name='type',
            field=models.CharField(choices=[('dns', 'DNS'), ('ip', 'IP')], default='dns', max_length=8),
        ),
    ]
