# Generated by Django 6.0.8 on 2026-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0059_alter_acmeauthorization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmeorder',
            name='error',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
