# This file is part of django-ca (https://github.com/mathiasertl/django-ca).
#
# django-ca is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# django-ca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with django-ca. If not, see
# <http://www.gnu.org/licenses/>.

"""Pydantic models representing messages exchanged between various parts of the system."""

from datetime import UTC, datetime

from pydantic import BaseModel, Field, JsonValue

from django_ca.conf import model_settings
from django_ca.pydantic.base import DATETIME_EXAMPLE
from django_ca.pydantic.extensions import ConfigurableExtensionModel
from django_ca.pydantic.name import NameModel
from django_ca.pydantic.type_aliases import CSRType, Serial
from django_ca.typehints import SignatureHashAlgorithmName


class GenerateOCSPKeyMessage(BaseModel):
    """Schema for a message to generate a OCSP certificate key.

    This message is used by :py:class:`~django_ca.tasks.generate_ocsp_key` to parse parameters.
    """

    serial: Serial
    force: bool = False


class ResignCertificateMessage(BaseModel):
    """Schema for resigning an existing certificate."""

    key_backend_options: dict[str, JsonValue] = Field(
        default_factory=dict,
        description="Options for the key backend. Valid values depend on the key backend of the certificate "
        "authority. If not passed, the key backend must be configured for automatic signing in the backend.",
    )
    not_after: datetime | None = Field(
        description="When the certificate is due to expire, defaults to the CA_DEFAULT_EXPIRES setting.",
        default_factory=lambda: datetime.now(tz=UTC) + model_settings.CA_DEFAULT_EXPIRES,
        json_schema_extra={"example": DATETIME_EXAMPLE},
    )


class SignCertificateMessage(ResignCertificateMessage):
    """Schema for signing certificates."""

    algorithm: SignatureHashAlgorithmName | None = Field(
        default=None,
        description="Hash algorithm used for signing (default: same as in the certificate authority).",
        # TODO: check if this is necessary since we now have a 'literal'
        # json_schema_extra={"enum": list(sorted(HASH_ALGORITHM_TYPES))},
    )
    autogenerated: bool = Field(
        default=False, description="If the certificate should be marked as auto-generated."
    )
    csr: CSRType = Field(
        title="CSR",
        description="The certificate signing request (CSR) in PEM format",
        json_schema_extra={
            "example": "-----BEGIN CERTIFICATE REQUEST-----\n...\n-----END CERTIFICATE REQUEST-----\n"
        },
    )
    extensions: list[ConfigurableExtensionModel] | None = Field(
        default_factory=list, description="**Optional** additional extensions to add to the certificate."
    )
    profile: str = Field(
        description="Issue the certificate with the given profile.",
        default=model_settings.CA_DEFAULT_PROFILE,
        json_schema_extra={"enum": list(sorted(model_settings.CA_PROFILES))},
    )
    subject: NameModel = Field(description="The subject as list of name attributes.")
