# Dockerfile to test wheels in an isolated environment

ARG IMAGE
FROM $IMAGE as build
WORKDIR /work/

# Install uv: https://docs.astral.sh/uv/guides/integration/docker/
COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /uvx /bin/

# Add files necessary to build the wheel
ADD LICENSE MANIFEST.in README.md pyproject.toml ./
ADD docs/source/intro.rst docs/source/
ADD ca/django_ca ca/django_ca

# Build wheel
RUN uv build

FROM $IMAGE
COPY --from=build /work/dist/* /work/dist/
CMD cp /work/dist/* /dist/
