# This file is part of django-ca (https://github.com/mathiasertl/django-ca).
#
# django-ca is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# django-ca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with django-ca. If not, see
# <http://www.gnu.org/licenses/>.

"""Messages for Celery tasks."""

from pydantic import AwareDatetime, Field

from django_ca.celery import CeleryMessageModel
from django_ca.conf import model_settings
from django_ca.constants import SIGNATURE_HASH_ALGORITHM_TYPES
from django_ca.pydantic import NameModel
from django_ca.pydantic.extensions import ConfigurableExtensionModel
from django_ca.pydantic.type_aliases import CSRType, Serial
from django_ca.typehints import JSON, SignatureHashAlgorithm, SignatureHashAlgorithmName

KeyBackendOptions = dict[str, JSON]


class UseCertificateAuthorityCeleryMessage(CeleryMessageModel):
    """Parameters for using a single certificate authority."""

    serial: Serial
    key_backend_options: KeyBackendOptions = Field(default_factory=dict)


class UseMultipleCertificateAuthoritiesCeleryMessage(CeleryMessageModel):
    """Parameters for using multiple certificate authorities."""

    serials: tuple[Serial, ...] = Field(default_factory=tuple)
    key_backend_options: dict[str, KeyBackendOptions] = Field(default_factory=dict)


class ApiSignCertificateMessage(CeleryMessageModel):
    """Parameters for ``django_ca.tasks.api_sign_certificate``."""

    order_pk: int
    csr: CSRType
    subject: NameModel
    algorithm: SignatureHashAlgorithmName | None = None
    not_after: AwareDatetime | None = None
    extensions: list[ConfigurableExtensionModel] = Field(default_factory=list)
    profile: str = model_settings.CA_DEFAULT_PROFILE
    autogenerated: bool = False
    key_backend_options: KeyBackendOptions = Field(default_factory=dict)

    def get_algorithm(self) -> SignatureHashAlgorithm | None:
        """Get algorithm class if set."""
        if self.algorithm is not None:
            return SIGNATURE_HASH_ALGORITHM_TYPES[self.algorithm]()
        return None
