# This file is part of django-ca (https://github.com/mathiasertl/django-ca).
#
# django-ca is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# django-ca is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with django-ca. If not, see
# <http://www.gnu.org/licenses/>.

"""Pydantic Schemas for the API."""

from datetime import datetime

from ninja import Field, ModelSchema, Schema

from django_ca.conf import model_settings
from django_ca.constants import ReasonFlags
from django_ca.models import CertificateAuthority, CertificateOrder
from django_ca.pydantic.base import DATETIME_EXAMPLE
from django_ca.pydantic.extensions import (
    AuthorityInformationAccessModel,
    CertificatePoliciesModel,
    CRLDistributionPointsModel,
    IssuerAlternativeNameModel,
)


class CertificateAuthorityFilterSchema(Schema):
    """Filter-schema for listing certificate authorities."""

    expired: bool = Field(default=False, description="Include expired CAs.")


class CertificateAuthorityUpdateSchema(ModelSchema):
    """Schema for updating certificate authorities."""

    name: str | None = Field(
        description="The human-readable name of the certificate authority.",
        default=None,
        json_schema_extra={"required": False},
    )
    sign_authority_information_access: AuthorityInformationAccessModel | None = Field(
        default=None,
        json_schema_extra={
            "description": "The Authority Information Access extension added to newly signed certificates."
        },
    )
    sign_certificate_policies: CertificatePoliciesModel | None = Field(
        default=None,
        json_schema_extra={
            "description": "The Certificate Policies extension added to newly signed certificates."
        },
    )
    sign_crl_distribution_points: CRLDistributionPointsModel | None = Field(
        default=None,
        json_schema_extra={
            "description": "The CRL Distribution Points extension added to newly signed certificates."
        },
    )
    sign_issuer_alternative_name: IssuerAlternativeNameModel | None = Field(
        default=None,
        json_schema_extra={
            "description": "The Issuer Alternative Name extension added to newly signed certificates."
        },
    )

    class Meta:  # pylint: disable=missing-class-docstring
        model = CertificateAuthority
        fields = (
            "name",
            "caa_identity",
            "website",
            "terms_of_service",
            "sign_authority_information_access",
            "sign_certificate_policies",
            "sign_crl_distribution_points",
            "sign_issuer_alternative_name",
            "ocsp_responder_key_validity",
            "ocsp_response_validity",
            "acme_enabled",
            "acme_registration",
            "acme_profile",
            "acme_requires_contact",
        )
        fields_optional = "__all__"


class CertificateOrderSchema(ModelSchema):
    """Schema for certificate orders."""

    serial: str | None = Field(alias="certificate.serial", default=None)
    created: datetime = Field(
        description="When the order was created.", json_schema_extra={"example": DATETIME_EXAMPLE}
    )
    updated: datetime = Field(
        description="When the order was last updated.", json_schema_extra={"example": DATETIME_EXAMPLE}
    )

    class Meta:  # pylint: disable=missing-class-docstring
        model = CertificateOrder
        fields = sorted(["created", "updated", "slug", "status"])


class CertificateFilterSchema(Schema):
    """Filter schema for certificates."""

    autogenerated: bool = Field(
        default=False, description="Include auto-generated certificates (e.g. OCSP responder certificates)."
    )
    expired: bool = Field(default=False, description="Include expired certificates.")
    profile: str | None = Field(
        description="Only return certificates generated with the given profile.",
        default=None,
        json_schema_extra={"enum": list(sorted(model_settings.CA_PROFILES))},
    )
    revoked: bool = Field(default=False, description="Include revoked certificates.")


class RevokeCertificateSchema(Schema):
    """Schema for revoking certificates."""

    compromised: datetime | None = Field(default=None, description="When the certificate was compromised.")

    reason: ReasonFlags = Field(
        default=ReasonFlags.unspecified,
        description="""The reason why the certificate was revoked. Valid values are `unspecified`,
        `keyCompromise`, `cACompromise`, `affiliationChanged`, `superseeded`, `cessationOfOperation`, 
        `certificateHold`, `privilegeWithdrawn`, `aACompromise` and `removeFromCRL`.""",
    )
