[tool.ruff]
extend = "../../../pyproject.toml"

line-length = 90

[tool.ruff.lint]
extend-ignore = [
    "D100",  # Missing docstring in public module - examples don't need docs
    "D101",  # Missing docstring in public class - examples don't need docs
]
